// Run with playwright-cli run-code --filename=prototypes/touch-terminal/browser-smoke.js
// Existing isolated page must point to serve.py. No installed IME is accessed.
async (page) => {
  const base = page.url().split('/').slice(0,3).join('/');
  if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(base)) throw new Error('Use the loopback prototype server');
  const checks = [], errors = [], external = [];
  const assert = (condition, message) => { if (!condition) throw new Error(message); };
  page.on('pageerror', error => errors.push(String(error)));
  page.on('request', request => { if (!request.url().startsWith(base + '/')) external.push(request.url()); });
  await page.setViewportSize({width:1440,height:1100});
  await page.goto(base);
  await page.locator('.sound-key').last().waitFor();
  assert(await page.locator('.sound-key').count() === 60, '60 independent keys');
  assert(await page.locator('#load-error').isHidden(), 'data loads');
  const data = await page.evaluate(async () => ({layout:await (await fetch('./data/layout.json')).json(),demo:await (await fetch('./data/demo.json')).json()}));
  assert(data.layout.touchTemplate.format === 'keyboard-layout-editor.com', 'KLE format recorded');
  assert(data.layout.touchTemplate.bounds.width === 10 && data.layout.touchTemplate.bounds.height === 6, 'KLE bounds recorded');
  assert(data.layout.sources.some(source => source.path.endsWith('.kle.json')), 'KLE source provenance recorded');
  const firstBox = await page.locator('[data-id="N01"]').boundingBox();
  const rowEndBox = await page.locator('[data-id="N10"]').boundingBox();
  const nextRowBox = await page.locator('[data-id="N11"]').boundingBox();
  assert(Math.abs(firstBox.y - rowEndBox.y) < 1, 'KLE first row geometry');
  assert(nextRowBox.y > firstBox.y + firstBox.height, 'KLE row separation');
  assert((await page.locator('#touch-template-label').innerText()).includes('10 × 6 KLE u'), 'KLE identity visible');
  checks.push('strict KLE geometry and source identity rendered');
  const clear = async () => { if (await page.locator('#clear').isEnabled()) await page.locator('#clear').click(); };
  // Each release must append exactly one ID, including IDs with a shared key.
  for (const key of data.layout.keys) {
    await page.locator(`[data-id="${key.id}"]`).click();
    assert(await page.locator('#composition').innerText() === `${key.id} ${key.label}`, `single release ${key.id}`);
    assert(await page.locator('#code').innerText() === key.key, `projection ${key.id}`);
    await clear();
  }
  checks.push('all 60 mouse releases dispatch once; shared IDs remain independent');
  const ni = data.demo.examples.find(e => e.id === 'ni3');
  for (const id of ni.ids) await page.locator(`[data-id="${id}"]`).click();
  assert(await page.locator('.candidate').count() === ni.candidates.length, 'manual composition candidates');
  await page.locator('#backspace').click();
  assert(await page.locator('.candidate').count() === 0, 'backspace recomputes candidates');
  await page.locator(`[data-id="${ni.ids.at(-1)}"]`).click();
  await page.keyboard.press('Shift+Digit2');
  assert(await page.locator('.candidate[aria-pressed="true"]').getAttribute('data-candidate-id') === ni.candidates[1].id, 'Shift ordinal selects');
  assert(await page.locator('#committed').innerText() === '等待第一次确认', 'selection does not commit');
  await page.keyboard.press('Enter');
  assert(await page.locator('#committed').innerText() === ni.candidates[1].text, 'explicit confirm');
  await page.keyboard.press('Backspace');
  assert(await page.locator('#committed').innerText() === ni.candidates[1].text, 'empty backspace preserves committed text');
  await page.locator('[data-example-id="ni3"]').click();
  await page.keyboard.press('1');
  assert(await page.locator('#code').innerText() === ni.code + '1', 'bare digit composes while candidates visible');
  assert(await page.locator('#confirm').isDisabled(), 'unmatched composition cannot confirm');
  checks.push('manual composition, backspace, Shift selection, explicit confirmation, bare digits');
  await page.locator('[data-example-id="shi4"]').click();
  assert(await page.locator('.candidate').count() === 9, 'first candidate page');
  await page.locator('#next').click();
  assert(await page.locator('.candidate').count() === 4, 'second candidate page');
  const selected = await page.locator('.candidate').nth(2).getAttribute('data-candidate-id');
  await page.locator('.candidate').nth(2).click();
  assert(await page.evaluate(() => document.activeElement.id) === 'keyboard', 'candidate restores keyboard focus');
  await page.keyboard.press('Enter');
  const shi = data.demo.examples.find(e => e.id === 'shi4');
  assert((await page.locator('#committed').innerText()).endsWith(shi.candidates.find(c => c.id === selected).text), 'page candidate commit');
  checks.push('13-candidate pagination, tap selects only, focus retained');
  const box = await page.locator('[data-id="N01"]').boundingBox();
  await page.mouse.move(box.x + box.width/2,box.y + box.height/2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width + 12,box.y + box.height/2);
  await page.mouse.move(box.x + box.width/2,box.y + box.height/2);
  await page.mouse.up();
  assert(await page.locator('#code').innerText() === '—', 'drag outside then return must cancel');
  await page.locator('[data-id="N01"]').focus();
  await page.keyboard.press('Space');
  assert(await page.locator('#code').innerText() === 'b', 'keyboard/AT activation once');
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  assert(await page.locator('#code').innerText() === '—', 'blur cancels unconfirmed composition');
  checks.push('drag cancellation, keyboard activation, synthetic blur preserves confirmed text');
  await page.locator('#drill').click();
  for (const key of data.layout.keys) await page.locator(`[data-id="${key.id}"]`).click();
  assert((await page.locator('#drill-status').innerText()).includes('已覆盖 60/60，总点按 60，重复 0'), '60-key coverage drill');
  await page.locator('#target-drill').click();
  for (let i=0;i<60;i++) await page.locator('.sound-key.target').click();
  assert((await page.locator('#drill-status').innerText()).includes('命中 60，错键 0'), 'prompted target drill');
  const downloadEvent = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadEvent;
  const reportStream = await download.createReadStream();
  let reportText = '';
  for await (const chunk of reportStream) reportText += chunk;
  const report = JSON.parse(reportText);
  await download.saveAs('output/playwright/touch-terminal-session.json');
  assert(await download.failure() === null, 'JSON download succeeds');
  assert(report.formatVersion === 3, 'baseline report v3');
  assert(report.drills.length === 2, 'coverage and target drills retained');
  assert(report.drills[0].unique === 60 && report.drills[0].duplicate === 0, 'coverage summary retained');
  assert(report.drills[1].correct === 60 && report.drills[1].wrong === 0, 'target summary retained');
  assert(report.touches.some(touch => Number.isFinite(touch.pointer?.up?.keyLocal?.x)), 'pointer coordinates retained');
  checks.push('separate coverage/target drills, pointer geometry and JSON v3 export');
  await clear();
  await page.locator('[data-example-id="ni3"]').click();
  await page.screenshot({path:'output/playwright/touch-terminal-desktop.png',fullPage:true});

  // Browser-emulated touch verifies pointer dispatch; it is not physical evidence.
  const context = await page.context().browser().newContext({viewport:{width:800,height:1100},hasTouch:true,isMobile:true,deviceScaleFactor:1});
  try {
    const touchPage = await context.newPage();
    touchPage.on('pageerror', error => errors.push(String(error)));
    touchPage.on('request', request => { if (!request.url().startsWith(base + '/')) external.push(request.url()); });
    await touchPage.goto(base);
    await touchPage.locator('.sound-key').last().waitFor();
    await touchPage.locator('[data-id="N26"]').tap();
    assert((await touchPage.locator('#composition').innerText()).startsWith('N26 '), 'touch preserves shared ID');
    assert(await touchPage.locator('#code').innerText() === "'", 'touch release no duplicate');
    await touchPage.locator('#clear').tap();
    await touchPage.locator('[data-id="N01"]').scrollIntoViewIfNeeded();
    const touchBox = await touchPage.locator('[data-id="N01"]').boundingBox();
    const cdp = await context.newCDPSession(touchPage);
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchBox.x+20,y:touchBox.y+25}]});
    await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
    assert(await touchPage.locator('#code').innerText() === '—', 'touchCancel does not input');
    checks.push('emulated touch tap exactly once and CDP touchCancel');
    await touchPage.setViewportSize({width:390,height:844});
    await touchPage.locator('[data-id="N01"]').scrollIntoViewIfNeeded();
    const b = await touchPage.locator('[data-id="N03"]').boundingBox();
    const scrollBefore = await touchPage.locator('.keyboard-scroll').evaluate(el => el.scrollLeft);
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});
    for (const offset of [30,70,110]) await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+b.width/2-offset,y:b.y+b.height/2}]});
    await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
    await touchPage.waitForFunction(old => document.querySelector('.keyboard-scroll').scrollLeft > old,scrollBefore);
    assert(await touchPage.locator('#code').innerText() === '—', 'touch scroll cancels key activation');
    assert(await touchPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'narrow page has no document-wide overflow');
    await touchPage.screenshot({path:'output/playwright/touch-terminal-narrow.png',fullPage:true});
    checks.push('390px emulated touch scroll, cancellation, no page overflow');
  } finally { await context.close(); }
  assert(errors.length === 0, `browser errors: ${errors.join('; ')}`);
  assert(external.length === 0, `unexpected external requests: ${external.join('; ')}`);
  return {ok:true,checks,errors,external,hardwareAcceptance:false};
}
