package userlexicon

const (
	SourceFileName       = "yime_user_phrases.txt"
	DefaultEntryWeight   = "1000000"
	sourceHeaderLine1    = "# PIME Yime user phrases"
	sourceHeaderLine2    = "# format: phrase<TAB>numeric-tone-pinyin<TAB>weight"
	sourceHeaderExample  = "# example: 中国\tzhong1 guo2\t1000000"
	generatedHeaderLine1 = "# Generated by PIME Yime from yime_user_phrases.txt"
	generatedHeaderLine2 = "# format: phrase<TAB>code<TAB>weight"
)

// Entry is a user lexicon source entry.
type Entry struct {
	Phrase     string
	Pinyin     string
	Weight     string
	LineNumber int
}

// Clone returns a shallow copy of the entry without line number metadata.
func (e Entry) Clone() Entry {
	return Entry{Phrase: e.Phrase, Pinyin: e.Pinyin, Weight: e.Weight}
}
